In [1]:
import numpy as np
import pandas as pd

# Series

In [2]:
ls = [1,2,3,4,5]
ts = pd.Series(ls)
ts

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
ts = pd.Series(ls, index=['a','b','c','d','e'])

In [4]:
bs=pd.Series(ls, index=['-','-','-','-','-']) #인덱스는 마음대로 지정가능

In [5]:
bs['-']

-    1
-    2
-    3
-    4
-    5
dtype: int64

In [6]:
ts['b']

2

In [7]:
ts['e'] =10
ts

a     1
b     2
c     3
d     4
e    10
dtype: int64

boolean indexing

In [8]:
ts[ts>3]

d     4
e    10
dtype: int64

In [9]:
ts*2 #Broadcasting 발생

a     2
b     4
c     6
d     8
e    20
dtype: int64

In [10]:
ts.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [11]:
ts.values

array([ 1,  2,  3,  4, 10], dtype=int64)

In [12]:
ts.index = ['가', '나','다','라','마'] #ts의 인덱스만 바꿀 수도 있다
ts

가     1
나     2
다     3
라     4
마    10
dtype: int64

# DataFrame

In [39]:
rData = {'first_name':['jason', np.nan, 'tina', 'jake', 'amy'],
         'last_name':['miller', np.nan, 'all', 'miler', 'coozer'],
         'age':[42,np.nan, 36,24,73],
         'sex':['m', np.nan, 'f', 'm', 'f'],
         'pretestscore':[4, np.nan, np.nan, 2,3],
         'posttestscore':[24,np.nan, np.nan, 62, 70]}

In [38]:
df = pd.DataFrame(rData)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
first_name       4 non-null object
last_name        4 non-null object
age              4 non-null float64
sex              4 non-null object
pretestscore     3 non-null float64
posttestscore    3 non-null float64
dtypes: float64(3), object(3)
memory usage: 368.0+ bytes


In [15]:
df1 = pd.DataFrame(rData, columns=['first_name','last_name'])
df1

first_name last_name
0      jason    miller
1        NaN       NaN
2       tina       all
3       jake     miler
4        amy    coozer

In [16]:
df.columns

Index(['first_name', 'last_name', 'age', 'sex', 'pretestscore',
       'posttestscore'],
      dtype='object')

In [30]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
df1.columns = ['fn','ln']
df1

fn      ln
0  jason  miller
1    NaN     NaN
2   tina     all
3   jake   miler
4    amy  coozer

In [36]:
df['age']

0    42.0
1     NaN
2    36.0
3    24.0
4    73.0
Name: age, dtype: float64

In [39]:
df[['first_name','last_name']]

first_name last_name
0      jason    miller
1        NaN       NaN
2       tina       all
3       jake     miler
4        amy    coozer

In [43]:
df.first_name #속성접근으로 할경우 값을 변경할 수 없고 컬럼명에 공백이 있을경우 사용할 수 없다

0    jason
1      NaN
2     tina
3     jake
4      amy
Name: first_name, dtype: object

# dataframe에서 row에 접근할 때
df.loc[인덱스]<br>
df.iloc[인덱스]

In [68]:
df.index= ['a','b','c','d','e']
df

first_name last_name   age  sex  pretestscore  posttestscore
a      jason    miller  42.0    m           4.0           24.0
b        NaN       NaN   NaN  NaN           NaN            NaN
c       tina       all  36.0    f           NaN            NaN
d       jake     miler  24.0    m           2.0           62.0
e        amy    coozer  73.0    f           3.0           70.0

In [50]:
df.loc['c']

first_name       tina
last_name         all
age                36
ses                 f
pretestscore      NaN
posttestscore     NaN
Name: c, dtype: object

In [53]:
df.loc[['c','d']]

first_name last_name   age ses  pretestscore  posttestscore
c       tina       all  36.0   f           NaN            NaN
d       jake     miler  24.0   m           2.0           62.0

In [54]:
df.iloc[2]

first_name       tina
last_name         all
age                36
ses                 f
pretestscore      NaN
posttestscore     NaN
Name: c, dtype: object

In [55]:
df.iloc[[0,2]]

first_name last_name   age ses  pretestscore  posttestscore
a      jason    miller  42.0   m           4.0           24.0
c       tina       all  36.0   f           NaN            NaN

In [57]:
df.loc['a','last_name'] # '인덱스','컬럼명'으로 인덱스와 컬럼을 동시검색가능

'miller'

In [59]:
df.iloc[0,1] # '인덱스', '컬럼의 인덱스'로 인덱스와 컬럼 동시검색가능

'miller'

In [69]:
df.loc['a':'c','last_name':'sex']

last_name   age  sex
a    miller  42.0    m
b       NaN   NaN  NaN
c       all  36.0    f

In [70]:
df.iloc[0:3, 1:4]

last_name   age  sex
a    miller  42.0    m
b       NaN   NaN  NaN
c       all  36.0    f

In [71]:
df.loc['c':'e','sex':'posttestscore']

sex  pretestscore  posttestscore
c   f           NaN            NaN
d   m           2.0           62.0
e   f           3.0           70.0

In [72]:
df.iloc[2:, 3:]

sex  pretestscore  posttestscore
c   f           NaN            NaN
d   m           2.0           62.0
e   f           3.0           70.0

In [77]:
# all, miler, Nan, 2.0
df.loc['c':'d','last_name':'pretestscore':3]
df.loc['c':'d',['last_name','pretestscore']]
df

first_name last_name   age  sex  pretestscore  posttestscore
a      jason    miller  42.0    m           4.0           24.0
b        NaN       NaN   NaN  NaN           NaN            NaN
c       tina       all  36.0    f           NaN            NaN
d       jake     miler  24.0    m           2.0           62.0
e        amy    coozer  73.0    f           3.0           70.0

In [87]:
#'age'가 40이상인 데이터를 추출/이름만/값만/리스트로바꿔서 보여주기
df[df['age']>40]['last_name'].values.tolist()

['miller', 'coozer']

In [92]:
#'jason'의 pretestscore는?
df[df['first_name'] == 'jason']['pretestscore']

a    4.0
Name: pretestscore, dtype: float64

In [93]:
#여성의 평균나이
sum(df[df['sex']=='f']['age'])/len(df[df['sex']=='f'])

54.5

In [96]:
#여성의 평균나이
np.mean(df[df['sex']=='f']['age'].values)

54.5

In [95]:
#여성의 평균나이
df[df['sex']=='f']['age'].mean() # <- 판다스는 넘파이에서 나왔으므로 바로 넘파이의 함수 적용 가능

54.5

In [103]:
#최고령자의 이름
df[df['age']==max(df['age'])][['first_name','last_name']].values.tolist()

[['amy', 'coozer']]

# Comumn추가

In [107]:
df

first_name last_name   age  sex  pretestscore  posttestscore     addr
a      jason    miller  42.0    m           4.0           24.0    seoul
b        NaN       NaN   NaN  NaN           NaN            NaN  incheon
c       tina       all  36.0    f           NaN            NaN  gwangju
d       jake     miler  24.0    m           2.0           62.0    pusan
e        amy    coozer  73.0    f           3.0           70.0   dajeon

In [110]:
df['addr']=['seoul', 'incheon', 'gwangju','pusan','dajeon'] #새로운 칼럼으로 자료를 추가하면 연장됨

In [109]:
df['age']=[42,24,46,46,32] #기존 컬럼에 자료룰 추가시 덮어씀
df

first_name last_name  age  sex  pretestscore  posttestscore     addr
a      jason    miller   42    m           4.0           24.0    seoul
b        NaN       NaN   24  NaN           NaN            NaN  incheon
c       tina       all   46    f           NaN            NaN  gwangju
d       jake     miler   46    m           2.0           62.0    pusan
e        amy    coozer   32    f           3.0           70.0   dajeon

In [111]:
df.iloc[1,3] = 'f'
df

first_name last_name  age sex  pretestscore  posttestscore     addr
a      jason    miller   42   m           4.0           24.0    seoul
b        NaN       NaN   24   f           NaN            NaN  incheon
c       tina       all   46   f           NaN            NaN  gwangju
d       jake     miler   46   m           2.0           62.0    pusan
e        amy    coozer   32   f           3.0           70.0   dajeon

# rename(columns={'x':'x1', 'y':'y1',....})

In [114]:
df.rename(columns={'first_name':'fn', 'last_name':'ln'}) #바꾼컬럼명을 보여주지만 원본은 변하지 않음

fn      ln  age sex  pretestscore  posttestscore     addr
a  jason  miller   42   m           4.0           24.0    seoul
b    NaN     NaN   24   f           NaN            NaN  incheon
c   tina     all   46   f           NaN            NaN  gwangju
d   jake   miler   46   m           2.0           62.0    pusan
e    amy  coozer   32   f           3.0           70.0   dajeon

In [115]:
df.rename(columns={'first_name':'fn', 'last_name':'ln'}, inplace=True) #원본까지 변경
df

fn      ln  age sex  pretestscore  posttestscore     addr
a  jason  miller   42   m           4.0           24.0    seoul
b    NaN     NaN   24   f           NaN            NaN  incheon
c   tina     all   46   f           NaN            NaN  gwangju
d   jake   miler   46   m           2.0           62.0    pusan
e    amy  coozer   32   f           3.0           70.0   dajeon

In [116]:
df.columns = ['fn', 'ln', 'age', 'sex' , 'prtest', 'potest','addr']
df

fn      ln  age sex  prtest  potest     addr
a  jason  miller   42   m     4.0    24.0    seoul
b    NaN     NaN   24   f     NaN     NaN  incheon
c   tina     all   46   f     NaN     NaN  gwangju
d   jake   miler   46   m     2.0    62.0    pusan
e    amy  coozer   32   f     3.0    70.0   dajeon

In [117]:
df.drop('addr', axis=1)

fn      ln  age sex  prtest  potest
a  jason  miller   42   m     4.0    24.0
b    NaN     NaN   24   f     NaN     NaN
c   tina     all   46   f     NaN     NaN
d   jake   miler   46   m     2.0    62.0
e    amy  coozer   32   f     3.0    70.0

In [119]:
df.to_csv('test.csv')

In [121]:
pd.read_csv('test.csv')

Unnamed: 0     fn      ln  age sex  prtest  potest     addr
0          a  jason  miller   42   m     4.0    24.0    seoul
1          b    NaN     NaN   24   f     NaN     NaN  incheon
2          c   tina     all   46   f     NaN     NaN  gwangju
3          d   jake   miler   46   m     2.0    62.0    pusan
4          e    amy  coozer   32   f     3.0    70.0   dajeon

In [120]:
pd.read_csv('test.csv', index_col=0)

fn      ln  age sex  prtest  potest     addr
a  jason  miller   42   m     4.0    24.0    seoul
b    NaN     NaN   24   f     NaN     NaN  incheon
c   tina     all   46   f     NaN     NaN  gwangju
d   jake   miler   46   m     2.0    62.0    pusan
e    amy  coozer   32   f     3.0    70.0   dajeon

In [151]:
np.random.randn(5)

array([ 0.39327833,  0.99453566,  0.55812341,  1.53381198, -1.20932797])

In [165]:
np.random.randint(5)

4

In [175]:
np.random.choice([1,2,3,4,5])

3

In [181]:
np.random.sample((5))

array([0.42706069, 0.06489296, 0.01350868, 0.8444406 , 0.21937431])

# 결측치처리(Null값 처리)

In [127]:
df = pd.DataFrame( np.random.rand(5,5), columns = ['one', 'two', 'three', 'four', 'five'], index= ['a','b','c','d','e'])
df

one       two     three      four      five
a  0.638492  0.834796  0.492407  0.674957  0.216263
b  0.261208  0.661282  0.230902  0.110613  0.764761
c  0.999017  0.625294  0.673026  0.804627  0.650881
d  0.284383  0.719942  0.397434  0.831575  0.980950
e  0.289992  0.939575  0.733002  0.780889  0.408917

In [129]:
df.iloc[1:3,1] = np.nan
df.iloc[2,2:4] = np.nan
df

one       two     three      four      five
a  0.638492  0.834796  0.492407  0.674957  0.216263
b  0.261208       NaN  0.230902  0.110613  0.764761
c  0.999017       NaN       NaN       NaN  0.650881
d  0.284383  0.719942  0.397434  0.831575  0.980950
e  0.289992  0.939575  0.733002  0.780889  0.408917

# isnull()
null값인지 아닌지 true/false로 반환한다.
# isnull().sum()
true =1 false=0이므로 true값의 갯수 =null값의 갯수가 반환된다.

In [131]:
df.isnull().sum(axis=0)

one      0
two      2
three    1
four     1
five     0
dtype: int64

In [132]:
df.isnull().sum(axis=1)

a    0
b    1
c    3
d    0
e    0
dtype: int64

# null값 처리
# 1.null값을 포함한 행이나 컬럼을 삭제=>dropna()
# 2.null값을 다른 값으로 대체=> fillna()

In [139]:
df.dropna() #null 포함 데이터 삭제

one       two     three      four      five
a  0.638492  0.834796  0.492407  0.674957  0.216263
d  0.284383  0.719942  0.397434  0.831575  0.980950
e  0.289992  0.939575  0.733002  0.780889  0.408917

In [140]:
df.dropna(axis=1) #null 포함 컬럼 삭제

one      five
a  0.638492  0.216263
b  0.261208  0.764761
c  0.999017  0.650881
d  0.284383  0.980950
e  0.289992  0.408917

In [142]:
df.dropna(how='all') #모든 데이터가 null값일때만 삭제

one       two     three      four      five
a  0.638492  0.834796  0.492407  0.674957  0.216263
b  0.261208       NaN  0.230902  0.110613  0.764761
c  0.999017       NaN       NaN       NaN  0.650881
d  0.284383  0.719942  0.397434  0.831575  0.980950
e  0.289992  0.939575  0.733002  0.780889  0.408917

In [143]:
df.dropna(thresh=3) #null값을 제외한 데이터가 3개이상이면 삭제하지 않음

one       two     three      four      five
a  0.638492  0.834796  0.492407  0.674957  0.216263
b  0.261208       NaN  0.230902  0.110613  0.764761
d  0.284383  0.719942  0.397434  0.831575  0.980950
e  0.289992  0.939575  0.733002  0.780889  0.408917

In [137]:
df.fillna(0)

one       two     three      four      five
a  0.638492  0.834796  0.492407  0.674957  0.216263
b  0.261208  0.000000  0.230902  0.110613  0.764761
c  0.999017  0.000000  0.000000  0.000000  0.650881
d  0.284383  0.719942  0.397434  0.831575  0.980950
e  0.289992  0.939575  0.733002  0.780889  0.408917

In [146]:
df.fillna(method='ffill') #null값에 바로 앞에 있는 데이터를 채워넣는다. bfill 뒤의 데이터를 채워 넣는다

one       two     three      four      five
a  0.638492  0.834796  0.492407  0.674957  0.216263
b  0.261208  0.834796  0.230902  0.110613  0.764761
c  0.999017  0.834796  0.230902  0.110613  0.650881
d  0.284383  0.719942  0.397434  0.831575  0.980950
e  0.289992  0.939575  0.733002  0.780889  0.408917

In [150]:
print(df['one'])

a    0.638492
b    0.261208
c    0.999017
d    0.284383
e    0.289992
Name: one, dtype: float64
