In [1]:
import numpy as np

# array()
np.array(요소들,데이터타입) 로 생성

배열.shape

배열.reshape

배열.ndim

In [3]:
a1 = np.array([1,4,5,6], float)
a1

array([1., 4., 5., 6.])

In [4]:
a1[1]

4.0

In [8]:
a1[1:3]

array([4., 5.])

In [11]:
type(a1[1])

numpy.float64

In [12]:
a1.shape

(4,)

In [15]:
np.array([1,3,4,'8']) # 데이터 타입을 명시하지 않을 경우 스트링 타입 리스트가 됨

array(['1', '3', '4', '8'], dtype='<U11')

In [16]:
np.array([1,3,4,'8'], float) # 데이터 타입을 명시하면 모든 원소가 해당 데이터 타입이 됨

array([1., 3., 4., 8.])

# 각 열의 갯수가 같아야 매트릭스가 된다!

In [24]:
mat = np.array([[1,3,5,6],[2,4,5,7],[5,4,2,3]]) 
mat

array([[1, 3, 5, 6],
       [2, 4, 5, 7],
       [5, 4, 2, 3]])

In [22]:
mat.shape

(3, 4)

In [23]:
mat.ndim

2

# reshape()
reshape로 배열의 size -> 원소의 갯수를 변경할 수 없다

In [28]:
a1 = [[1,2,3,4],[1,2,3,8]]
mat = np.array(a1)
mat

array([[1, 2, 3, 4],
       [1, 2, 3, 8]])

In [29]:
mat.shape

(2, 4)

## reshape()를 통해 2차원 매트릭스를 1차원 배열로 변환

In [30]:
mat.reshape(8)

array([1, 2, 3, 4, 1, 2, 3, 8])

In [32]:
mat.reshape(8).shape

(8,)

## reshape()를 통해 2차원 매트릭스를 3차원 공간으로 변환

In [33]:
mat.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 8]]])

In [34]:
mat.reshape(2,2,2).shape

(2, 2, 2)

In [36]:
mat.reshape(2,3,2)#size : 원소의 갯수가 변경될 수 없다.

ValueError: cannot reshape array of size 8 into shape (2,3,2)

# indexing

In [39]:
ts = np.array([[1,2,3],[4.5,5,6]], int)
ts

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
ts.shape

(2, 3)

In [42]:
ts[0,1]

2

In [43]:
ts[1,2]

6

In [44]:
ts[-1,-1]

6

In [45]:
ts[1,0]

4

In [46]:
ts[0,0] = 10

In [47]:
ts

array([[10,  2,  3],
       [ 4,  5,  6]])

In [49]:
tm = np.array([[1,2,3,4,5],[6,7,8,9,10]])
tm

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## 행 -row(가로), 하나의 데이터 값(data)
## 열 - column(세로), 데이터의 특성값(feature)

## indexing => arr[행idx, 열idx]

In [60]:
#8 출력
#2,3
#8,9,10
#3,4,8,9
#2,4,7,9
# 4,5,9,10

print(tm[1,2])
print(tm[0,1:3])
print(tm[1,2:])
print(tm[:,2:4])
print(tm[:,1::2])
print(tm[:,3:])

8
[2 3]
[ 8  9 10]
[[3 4]
 [8 9]]
[[2 4]
 [7 9]]
[[ 4  5]
 [ 9 10]]


# arange()

In [61]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
list(range(5,11))

[5, 6, 7, 8, 9, 10]

In [63]:
list(range(1,11,3))

[1, 4, 7, 10]

In [64]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [65]:
np.arange(1,11,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [66]:
arange(1,11,0.5)

NameError: name 'arange' is not defined

In [70]:
np.arange(1,11,0.1)

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8,
       10.9])

In [71]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [72]:
np.arange(30).reshape(10,3)# matrix 2차원 행렬

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [75]:
np.arange(30).reshape(2,5,3) # tensor 3차원 공간

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [77]:
np.arange(30)# vector 1차원 배열

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# Operation
numpy에서 연산 - element wise operation(동일한 인덱스의 원소끼리 연산)

In [80]:
ts = np.arange(30).reshape(5,6)
ts

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [81]:
ts.sum()

435

In [82]:
ts.mean()

14.5

In [83]:
ts.std() #표준편차

8.65544144839919

In [85]:
ts.var() #분산

74.91666666666667

In [86]:
#행방향
ts.sum(axis=1)

array([ 15,  51,  87, 123, 159])

In [87]:
#열방향
ts.sum(axis=0)

array([60, 65, 70, 75, 80, 85])

In [90]:
#행방향
ts.max(axis=1)

array([ 5, 11, 17, 23, 29])

In [91]:
#열방향
ts.max(axis=0)

array([24, 25, 26, 27, 28, 29])

In [92]:
ts.std(axis=1)

array([1.70782513, 1.70782513, 1.70782513, 1.70782513, 1.70782513])

# matrix operation

In [93]:
mat1 = np.arange(6).reshape(2,3)
mat1

array([[0, 1, 2],
       [3, 4, 5]])

In [94]:
mat2 = np.arange(6).reshape(2,3)
mat2

array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
mat1+mat2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [97]:
mat1 - mat2

array([[0, 0, 0],
       [0, 0, 0]])

In [99]:
mat1*mat2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [100]:
mat1/mat2

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.]])

In [101]:
mat1==mat2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [102]:
mat1>mat2

array([[False, False, False],
       [False, False, False]])

# Broadcasting
연산시 shape가 다른경우 같아지도록 확장되는 것

In [103]:
scalar = 3

In [104]:
mat1

array([[0, 1, 2],
       [3, 4, 5]])

In [105]:
mat1+scalar

array([[3, 4, 5],
       [6, 7, 8]])

In [107]:
mat3 = np.array([[3,3,3],[3,3,3]])
mat3

array([[3, 3, 3],
       [3, 3, 3]])

In [108]:
mat1+mat3

array([[3, 4, 5],
       [6, 7, 8]])

# vector

In [109]:
vect = np.array([3,3,3])
vect

array([3, 3, 3])

# all & any

In [110]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [112]:
np.any(a>5)

True

In [113]:
np.all(a>5)

False

In [114]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [115]:
np.all(a<10)

True

In [116]:
np.any(a<10)

True

# comparision operation

In [118]:
vec1 = np.array([1,3,0], float)
vec1

array([1., 3., 0.])

In [120]:
vec2 = np.array([5,2,1],float)
vec2

array([5., 2., 1.])

In [121]:
vec1>vec2

array([False,  True, False])

In [122]:
vec1<vec2

array([ True, False,  True])

# boolean index

In [123]:
vec = np.array([1,4,0,2,3,8,9,7], int)
vec

array([1, 4, 0, 2, 3, 8, 9, 7])

In [124]:
vec>3

array([False,  True, False, False, False,  True,  True,  True])

In [125]:
vec[[False,  True, False, False, False,  True,  True,  True]]

array([4, 8, 9, 7])

In [126]:
#vec에서 3보다 큰 요소만 출력

In [127]:
vec[vec>3]

array([4, 8, 9, 7])

In [129]:
#짝수만 출력
vec[vec%2==0]

array([4, 0, 2, 8])

In [131]:
#vec에 5보다 큰 값만 출력

print(vec[vec>5])

[8 9 7]


In [132]:
num = np.arange(1,101)

In [143]:
#num에서 20보다 크고 30보다 작은 3의 배수
num[(30>num)&(num>20)&(num%3==0)]

array([21, 24, 27])